apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-frontend-deployment
  labels:
    app: nginx-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-frontend
  template:
    metadata:
      labels:
        app: nginx-frontend
    spec:
      containers:
        - name: nginx-frontend
          image: nginx-frontend-image:1.0
          ports:
            - containerPort: 80
